### PR TITLE
Leaderboard UI Improvements

### LINKED ISSUE #61: UI improvements for /leaderboard
There are some small presentation issues present on the leaderboard when viewing on a small screen/mobile.

In particular:

- Icon spills out of button on small screens
- Table columns shift width when clicking on sort headers

### PR DESCRIPTION
**Pull request by yoshivb**
Resolves #61 

- [x] Icon spills out of button on small screens
- [x] Table columns shift width when clicking on sort headers

Resolved by adding a USkeleton that's the same size as the icons if there is no icon.
And forcing the width of the buttons to max-content.

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Is the USkeleton included with Nuxt or does it require a dependency?

**Comment by yoshivb** [comment]
Ah you are right, it is a Nuxt UI thing, it's just acting as an empty div anyways so I'll replace it as such.

**Comment by whitep4nth3r** [comment]
... should it be a span given that it probably shouldn't be a block level by default?

**Comment by yoshivb** [comment]
Hmm maybe? 
Tailwind CSS does make images block level by default https://tailwindcss.com/docs/preflight#images-are-block-level and since it's meant to mimic the image I think it makes more sense for it to be block level by default?

**Pull request merged**
