### PR TITLE
Add search with username for leaderboard

### PR DESCRIPTION
**Pull request by MhemedAbderrahmen**
Resolves https://github.com/whitep4nth3r/pantherworld/issues/32

A basic search, it is said that it might not be needed but since its a simple implementation i thought why not have it.

### CODE REVIEW

**Comment by MhemedAbderrahmen** [comment]
I just noticed that my PR is full of changes caused by my formatter, this is my bad I will fix this issue.

_PS: We will probably need some settings for linting and formatting the code enforced on this repo at some point, maybe i will open an issue for it._

**Comment by MhemedAbderrahmen** [comment]
Formatting changes removed.

**Comment by whitep4nth3r** [comment]
See comments here: https://github.com/whitep4nth3r/pantherworld/issues/32

**Comment by MhemedAbderrahmen** [comment]
Feature updated as requested.

Search with username now highlights and scrolls.
Simplified the UI as well

**Comment by whitep4nth3r** [comment]
Some things I noticed:

1. If the user is logged in and searches for themselves, the yellow highlight doesn't override the purple highlight for a logged in user
2. The accessibility for a yellow highlighted row isn't good enough at present, the text should be changed to a darker colour (zinc based, preferably)
3. I wonder if it's too complex to make it a fuzzy search? e.g. say I want to search for more than 1 of Matty's accounts (i.e. matty_twoshoes, matty_nshoes) — could we highlight more than one row?

**Comment by MhemedAbderrahmen** [comment]
PR Updated,

- Highlighting multiple users now works, similar to the browser, however the scroll felt weird when fuzzy searching, so I made it that once the username is submitted and a user is found it will scroll down to it.
- Also added the label and fixed the placeholder for the input.
- Fixed the purple color not overriding

**Comment by whitep4nth3r** [comment]
Couple more things:

1. The placeholder just needs to be `whitep4nth3r` and doesn't need `Example: `
2. Can we have a little bit of margin below the search input and button
3. Can the focus/active ring colour be the same as all the others across the site (some kind of emerald I think)
4. Can we add the scroll back in? I'd suggest that if there are more than one result, we scroll to the top one that is matched

**Comment by whitep4nth3r** [comment]
- [ ] nothing should happen if the input is empty and the search button is pressed or enter is pressed
- [ ] the description might be better saying "press submit or enter to scroll to the results"
- [ ] no icon on search button please
- [ ] make the search button say 'submit'
- [ ] 'Search for players' (change wording) should be a bit bigger and bolder??????
- [ ] remove "Click the column headers to sort and re-order." and you can make the "search for players" the same size as that

**Comment by whitep4nth3r** [comment]
Great work and thank you!

**Pull request merged**
